import { IconAccessPointOff } from '@tabler/icons-react';
import { Center } from '@mantine/core'
import { Text, Space } from '@mantine/core';
import Head from 'next/head'




export default function stream() {

    return (

        <><Head>
            <title> Live - Mennoniten Gemeinde</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Space h="xl" />
        <Text tt="uppercase" fz="xl" fs="italic" fw={700} ta="center">Es sind derzeit keine Live-Streams verfügbar. Bitte schauen Sie später wieder vorbei.</Text>
        <Center>
            
                <IconAccessPointOff className='stream-off' />
        
        </Center></>
    )
}