import { CardSection, Center } from '@mantine/core'
import { Text, Space, Card, Image, Badge, Button, Group, Title } from '@mantine/core';
import Head from 'next/head'
import { IconAccessPointOff } from '@tabler/icons-react';
import { IconAccessPoint } from '@tabler/icons-react';
import { IconUser } from '@tabler/icons-react';
import { IconCalendar } from '@tabler/icons-react';
import { useEffect, useState} from "react";
import {db, auth, storage } from "../../lib/config";
import {
    getDocs,
    collection,
    addDoc,
    deleteDoc,
    updateDoc,
    doc,
} from "firebase/firestore";
import React from 'react';
import { Fragment, useContext } from 'react';
import { useCallback } from 'react';
import Components from './components'
import { useMediaQuery } from '@mantine/core';


export default function Stream() {

  

    const [streamList, setStreamList] = useState([]);
    const streamCollectionRef = collection(db, "streamslive");

        const getStreamList = useCallback(async () => {
      try {
        const data = await getDocs(streamCollectionRef);
        const filterData = data.docs.map((doc) => ({
          ...doc.data(),
          id: doc.id,
        }));
        setStreamList(filterData);
      } catch (err) {
        console.error(err);
      }
    }, []);

    useEffect(() => {
      getStreamList();

  }, []);


  return (
    <>
      <Head>
        <title> Live - Mennoniten Gemeinde</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="Live Stream : Mennoniten Gemeinde" />
  <meta property="og:description" content="Mennoniten Gemeinde Designed and developed by David Dyck" />
  <meta property="og:image" content="https://firebasestorage.googleapis.com/v0/b/mennoniten-gemeinde-797ac.appspot.com/o/images%2Fkm5church-min3.png?alt=media&token=f7b705ff-e3d7-43f8-a205-82b2bf62aa9f" />
  <meta property="og:url" content="https://mennonitengemeinde.mx/streams/live" />
      </Head>
       {streamList.map((stream) => (
      <>


      <div key={stream.id}>
      <Space h="xl" /><div>
               <Center style={{ height: "100%", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
                   <Card shadow="sm" padding="lg" radius="md" withBorder className='stream-on-card'>
                       <IconAccessPoint color="red" size={30} />
                       <Group position="apart" mt="md" mb="xs" className="stream-meta">
                           <Center style={{ display: "flex", alignItems: "center" }} className="stream-speaker">
                               <Text fz="lg" className="stream-speaker-name"><IconUser size={18} />{stream.speaker}</Text>
                           </Center>
                           <Title weight={700} order={3} className="stream-title">{stream.Title}</Title>
                           <Center style={{ display: "flex", alignItems: "center" }} className="stream-date">
                               <Badge color="red" variant="light" size="lg" ta="center"><IconCalendar size={18} style={{ marginTop: "0.5rem" }} className="stream-date-badge"/> {stream.date}</Badge>
                           </Center>
                       </Group>
                       <Card.Section>
                           <div style={{ position: "relative", overflow: "hidden", width: "100%", paddingTop: "56.25%" }}>
                               <iframe
                                   src={`${stream.url}`}
                                   title="Live"
                                   frameBorder="0"
                                   allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                   allowFullScreen
                                   style={{ position: "absolute", top: "0", left: "0", width: "100%", height: "100%" }} />
                           </div>
                       </Card.Section>
                   </Card>
               </Center>
               <Space h="xl" />
           </div>
             </div>
           </>
      ))}
    </>
  );
}
