/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Center } from '@mantine/core'
import { Image } from '@mantine/core';
import Link from 'next/link'
import { Text, Space } from '@mantine/core';
import { AspectRatio } from '@mantine/core';



const links = [
  {
    link: '/',
    label: 'Hause',
    links: [],
  },
  {
    link: '/predigten',
    label: 'Predigten',
    links: [],

  },
  {
    link: '/live',
    label: 'Live',
    links: [],
  },

];







const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title> Live - Mennoniten - Gemeinde</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Space h="md" />
      <Center><h1>Live Streams</h1></Center>
      <Space h="md" />
      <AspectRatio ratio={16 / 9}>
      <iframe
        src="https://youtube.com/embed/ZMK6g1NLSqU"
        title="Live"
        frameBorder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowFullScreen
      />
    </AspectRatio>
    </>
  )
}