/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Center } from '@mantine/core'
import { Image } from '@mantine/core';
import Link from 'next/link'
import { Text, Space } from '@mantine/core';
import { AspectRatio } from '@mantine/core';
import { Loader } from '@mantine/core';
import { Card, Badge, Button, Group } from '@mantine/core';
import { SimpleGrid } from '@mantine/core';
import { MantineProvider } from '@mantine/core';
import { MediaQuery } from '@mantine/core';
import { IconCalendar } from '@tabler/icons';
import { collection, DocumentData, getDocs } from 'firebase/firestore';
import { db } from '../../firebase/clientApp';
import { useEffect, useState } from 'react';
import { Table } from '@mantine/core';
import { createStyles } from '@mantine/core';


const links = [
  {
    link: '/',
    label: 'Hause',
    links: [],
  },
  {
    link: '/predigten',
    label: 'Predigten',
    links: [],

  },
  {
    link: '/live',
    label: 'Live',
    links: [],
  },

];







const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [data, setData] = useState<DocumentData>([]);

  useEffect(() => {
      getDocs(collection(db, "streamslive")).then((querySnapshot) => {
          const items = querySnapshot.docs.map((doc) => doc.data());
          setData(items);
      });
  }, []);

  if (data.length === 0) {
      return <Center><Space h="xl" /><Loader variant="bars" /></Center>;
  }

  return (
    <>
    {data.map((item: DocumentData) => (
      <><Head>
        <title> Live - Mennoniten - Gemeinde</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head><Space w="md" /><Center><h1>{item.Title}</h1></Center><Space h="md" /><Center><p>{item.date}</p></Center><Center>
          <div className='stream-main-stream-page'>
            <iframe
              className='live-stream-main-iframe'
              src={item.url}
              title="Live"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen />
          </div>
        </Center></>
      ))}
    </>
  )
}