import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {useRouter} from 'next/router'

//importar firebase
import firebaseApp from '../../firebase/config'
import {getFirestore, collection, addDoc, getDocs, doc, deleteDoc, getDoc, setDoc} from 'firebase/firestore'
import { async } from '@firebase/util'
const db = getFirestore(firebaseApp)



export default function Home({productos}) {

  const router = useRouter()
  
  return (

    <>
   
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <Link href="/formulario">
          <a><button className='btn btn-primary mb-4'>Agregar producto</button></a>
        </Link>
        
        <div >
        {productos.map((product) => (
          <div  key={product.id}>
            <h5 >{product.title}</h5>
            <p>{product.spekaer}$</p>
            <p>{product.date} und.</p>
            <button  onClick={()=>router.push(`/producto/${product.id}`)}>View</button>
          </div>
        ))}
        </div>
      </div>

      </>
    
  )
}

export const getServerSideProps = async(context)=>{
  const querySnapshot = await getDocs(collection(db,'sermons'))
                const docs = []
                querySnapshot.forEach((doc)=>{
                    docs.push({...doc.data(), id: doc.id})
                })

  return {
    props:{
      productos: docs
    }
  }
}